sensors:
  luftdaten:
    17314:
      name: Westminster Road, Easton
      start_date: 2018-10-06
      location:
        latitude: 51.4633
        longitude: -2.5549

    17316:
      name: Emmaus - Backfields House
      start_date: 2018-10-06
      location:
        latitude: 51.4608
        longitude: -2.5885

    17318:
      name: Emmaus - Shaftesbury House
      start_date: 2018-10-06
      location:
        latitude: 51.4525
        longitude: -2.5746

    17502:
      name: St Werburghs
      start_date: 2018-10-14
      location:
        latitude: 51.468
        longitude: -2.5718

    17459:
      name: St Paul's Learning Centre
      start_date: 2018-10-15
      location:
        latitude: 51.464363
        longitude: -2.582494

    19613:
      name: St Paul's Adventure Playground
      start_date: 2018-12-23
      location:
        latitude: 51.4649
        longitude: -2.5776

    17506:
      name: Easton Community Centre
      start_date: 2018-10-14
      location:
        latitude: 51.461797
        longitude: -2.562962
        
    19615:
      name: Bannerman School
      start_date: 2018-12-23
      location:
        latitude: 51.4638
        longitude: -2.5646              

    23644:
      name: Albion Road
      start_date: 2019-03-30
      location:
        latitude: 51.4658
        longitude: -2.5643    
        
    23646:
      name: May Park Primary School
      start_date: 2019-04-03
      location:
        latitude: 51.47186
        longitude: -2.55698  

    23650:
      name: Stapleton Road
      start_date: 2019-03-30
      location:
        latitude: 51.47289
        longitude: -2.56137    

    23652:
      name: Albert Parade
      start_date: 2019-04-05
      location:
        latitude: 51.46071
        longitude: -2.55532  
        
    27458:
      name: Glenfrome Primary School
      start_date: 2019-06-10
      location:
        latitude: 51.478486
        longitude: -2.562907